#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STATE_FILE="${ROOT_DIR}/.install/install-state.env"
LOG_FILE="/tmp/corporate-ai-uninstall-$(date +%Y%m%d-%H%M%S).log"
MANAGED_OVERRIDE_MARKER="# Managed by Corporate AI Assistant install.sh"

readonly ROOT_DIR
readonly STATE_FILE
readonly LOG_FILE
readonly MANAGED_OVERRIDE_MARKER

DRY_RUN=0
ASSUME_YES=0

print_info() {
    printf "[INFO] %s\n" "$1"
}

print_success() {
    printf "[OK] %s\n" "$1"
}

print_warning() {
    printf "[WARN] %s\n" "$1"
}

print_error() {
    printf "[ERROR] %s\n" "$1" >&2
}

die() {
    print_error "$1"
    print_error "Uninstall log: ${LOG_FILE}"
    exit 1
}

usage() {
    cat <<EOF
Usage: bash uninstall.sh [--dry-run] [--yes] [--help]

Safe default uninstall for Corporate AI Assistant.

Removes by default:
- Docker Compose stack for this repository
- named Compose volumes for this repository
- project-local generated state such as .env, deploy/krb5.conf, installer-managed docker-compose.override.yml, .ollama, and .install
- deploy/certs only when the install manifest proves the certificates were generated by install.sh

Preserves:
- Docker Engine, Docker Compose plugin, Ollama CLI, apt repositories, and other host packages
- docker group membership and other host-level installer side effects
- deploy/sso keytab material
- repo-tracked files and unrelated Docker assets on the host

Options:
  --dry-run   Show what would be removed without changing anything
  --yes       Do not ask for confirmation
  --help      Show this help text
EOF
}

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

state_value() {
    local key="$1"
    [[ -f "${STATE_FILE}" ]] || return 1
    grep -E "^${key}=" "${STATE_FILE}" | tail -n 1 | cut -d'=' -f2- || true
}

extract_ollama_host_dir() {
    local match
    match="$(awk '/\/root\/\.ollama/ && $1 == "-" { print $2; exit }' "${ROOT_DIR}/docker-compose.yml" 2>/dev/null || true)"
    match="${match%%:/root/.ollama*}"
    printf "%s" "${match}"
}

resolve_project_path() {
    local path="$1"

    [[ -n "${path}" ]] || return 1
    if [[ "${path}" == /* ]]; then
        return 1
    fi

    path="${path#./}"
    path="${path#/}"
    printf "%s/%s" "${ROOT_DIR}" "${path}"
}

remove_path() {
    local label="$1"
    local path="$2"

    if [[ ! -e "${path}" && ! -L "${path}" ]]; then
        print_info "${label} not present: ${path}"
        return
    fi

    if [[ "${DRY_RUN}" -eq 1 ]]; then
        print_info "[dry-run] rm -rf -- ${path}"
        return
    fi

    rm -rf -- "${path}"
    print_success "Removed ${label}: ${path}"
}

run_compose_down() {
    if ! command_exists docker; then
        print_warning "Docker is not installed on this host. Skipping Docker Compose teardown."
        return
    fi

    if ! docker compose version >/dev/null 2>&1; then
        print_warning "Docker Compose plugin is not available. Skipping Docker Compose teardown."
        return
    fi

    if [[ "${DRY_RUN}" -eq 1 ]]; then
        print_info "[dry-run] (cd ${ROOT_DIR} && docker compose down --volumes --remove-orphans)"
        return
    fi

    (
        cd "${ROOT_DIR}"
        docker compose down --volumes --remove-orphans
    )
    print_success "Docker Compose stack removed for this repository"
}

remove_managed_override() {
    local override_file="${ROOT_DIR}/docker-compose.override.yml"

    if [[ ! -f "${override_file}" ]]; then
        print_info "docker-compose.override.yml not present"
        return
    fi

    if grep -qF "${MANAGED_OVERRIDE_MARKER}" "${override_file}"; then
        remove_path "installer-managed docker-compose.override.yml" "${override_file}"
        return
    fi

    print_warning "Preserving docker-compose.override.yml because it is not marked as installer-managed"
}

remove_tls_certs_if_manifest_allows() {
    local generated_tls
    local cert_dir="${ROOT_DIR}/deploy/certs"

    generated_tls="$(state_value "GENERATED_TLS_CERTS" || true)"
    if [[ "${generated_tls}" == "1" ]]; then
        remove_path "installer-generated TLS certificate directory" "${cert_dir}"
        return
    fi

    if [[ -d "${cert_dir}" ]]; then
        print_warning "Preserving deploy/certs because installer ownership is not proven"
    else
        print_info "deploy/certs not present"
    fi
}

remove_ollama_state() {
    local ollama_dir
    local resolved_dir

    ollama_dir="$(state_value "OLLAMA_HOST_DIR" || true)"
    if [[ -z "${ollama_dir}" ]]; then
        ollama_dir="$(extract_ollama_host_dir)"
    fi

    if [[ -z "${ollama_dir}" ]]; then
        print_info "No Ollama host directory was detected from manifest or docker-compose.yml"
        return
    fi

    if ! resolved_dir="$(resolve_project_path "${ollama_dir}")"; then
        print_warning "Preserving Ollama host directory because it resolves outside the repository scope: ${ollama_dir}"
        return
    fi

    remove_path "Ollama host directory" "${resolved_dir}"
}

confirm_uninstall() {
    local answer

    if [[ "${DRY_RUN}" -eq 1 || "${ASSUME_YES}" -eq 1 ]]; then
        return
    fi

    if [[ ! -t 0 ]]; then
        die "Non-interactive uninstall requires --yes"
    fi

    printf "This will remove the project stack, project-local generated state, and installer-owned runtime data from %s. Continue? [y/N]: " "${ROOT_DIR}"
    read -r answer
    case "${answer,,}" in
        y|yes)
            ;;
        *)
            die "Uninstall cancelled by user"
            ;;
    esac
}

parse_args() {
    while [[ "$#" -gt 0 ]]; do
        case "$1" in
            --dry-run)
                DRY_RUN=1
                ;;
            --yes)
                ASSUME_YES=1
                ;;
            --help|-h)
                usage
                exit 0
                ;;
            *)
                die "Unknown argument: $1"
                ;;
        esac
        shift
    done
}

print_plan() {
    print_info "Default uninstall scope:"
    print_info "- remove Docker Compose stack, network, and named volumes for this repository"
    print_info "- remove project-local .env, deploy/krb5.conf, installer-managed docker-compose.override.yml, .ollama, and .install"
    print_info "- remove deploy/certs only when the install manifest proves install.sh generated them"
    print_info "Preserved on purpose:"
    print_info "- Docker Engine, Docker Compose plugin, Ollama CLI, apt repositories, and other host packages"
    print_info "- docker group membership and host service changes"
    print_info "- deploy/sso keytab material"
    print_info "- repo-tracked files and unrelated Docker assets"
    print_info "Uninstall log: ${LOG_FILE}"
}

main() {
    parse_args "$@"
    exec > >(tee -a "${LOG_FILE}") 2>&1

    print_plan
    confirm_uninstall

    run_compose_down
    remove_path ".env" "${ROOT_DIR}/.env"
    remove_path "deploy/krb5.conf" "${ROOT_DIR}/deploy/krb5.conf"
    remove_managed_override
    remove_ollama_state
    remove_tls_certs_if_manifest_allows
    remove_path ".install" "${ROOT_DIR}/.install"

    print_success "Uninstall flow completed"
}

main "$@"
