#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STATE_FILE="${ROOT_DIR}/.install/install-state.env"
HOST_STATE_DIR="/var/lib/corporate-ai-assistant"
HOST_STATE_FILE="${HOST_STATE_DIR}/host-state.env"
RUN_TOKEN="$(date +%Y%m%d-%H%M%S)-$$"
LOG_FILE="/tmp/corporate-ai-uninstall-${RUN_TOKEN}.log"
HELPER_FILE="/tmp/corporate-ai-uninstall-helper-${RUN_TOKEN}.sh"
MANAGED_OVERRIDE_MARKER="# Managed by Corporate AI Assistant install.sh"

readonly ROOT_DIR
readonly STATE_FILE
readonly HOST_STATE_DIR
readonly HOST_STATE_FILE
readonly RUN_TOKEN
readonly LOG_FILE
readonly HELPER_FILE
readonly MANAGED_OVERRIDE_MARKER

DRY_RUN=0
ASSUME_YES=0
FACTORY_RESET=0
REMOVE_REPO=0

print_info() {
    printf "[INFO] %s\n" "$1"
}

print_success() {
    printf "[OK] %s\n" "$1"
}

print_warning() {
    printf "[WARN] %s\n" "$1"
}

print_error() {
    printf "[ERROR] %s\n" "$1" >&2
}

die() {
    print_error "$1"
    print_error "Uninstall log: ${LOG_FILE}"
    exit 1
}

usage() {
    cat <<EOF
Usage: bash uninstall.sh [--dry-run] [--yes] [--factory-reset] [--remove-repo] [--help]

Modes:
- default: safe cleanup of the project stack and project-local generated state
- --factory-reset: add manifest-driven host rollback for installer-owned dependencies where ownership is proven
- --remove-repo: after factory-reset, remove the repository directory through deferred background cleanup

Safe mode removes:
- Docker Compose stack for this repository
- named Compose volumes for this repository
- project-local generated state such as .env, deploy/krb5.conf, installer-managed docker-compose.override.yml, .ollama, and .install
- deploy/certs only when the install manifest proves the certificates were generated by install.sh

Factory-reset mode additionally removes or restores:
- exact apt packages that the manifest proves were installed by install.sh
- Docker apt repository files only when the manifest proves installer management
- docker group membership only when the manifest proves install.sh added it
- Docker and Ollama service state only when the manifest proves install.sh changed it
- Ollama host installation artifacts only when the manifest proves install.sh created them and records their paths

Preserved on purpose:
- unrelated Docker assets on the host
- deploy/sso keytab material
- host dependencies without manifest ownership proof
- repo-tracked files unless --remove-repo is used

Options:
  --dry-run        Show what would be removed or restored without changing anything
  --yes            Do not ask for confirmation
  --factory-reset  Enable manifest-driven host rollback
  --remove-repo    Remove the repository directory after cleanup; requires --factory-reset
  --help           Show this help text
EOF
}

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

as_root() {
    if [[ "${EUID}" -eq 0 ]]; then
        "$@"
        return
    fi

    command_exists sudo || die "sudo is required for this operation"
    sudo "$@"
}

bool_is_true() {
    [[ "${1:-0}" == "1" || "${1:-}" == "true" ]]
}

systemd_unit_exists() {
    command_exists systemctl && systemctl list-unit-files "$1" >/dev/null 2>&1
}

state_value_from_file() {
    local file="$1"
    local key="$2"

    [[ -f "${file}" ]] || return 1
    awk -F= -v key="${key}" '$1 == key { print substr($0, index($0, "=") + 1) }' "${file}" | tail -n 1
}

repo_state_value() {
    state_value_from_file "${STATE_FILE}" "$1"
}

host_state_value() {
    state_value_from_file "${HOST_STATE_FILE}" "$1"
}

preferred_state_value() {
    local key="$1"
    local value=""

    value="$(host_state_value "${key}" || true)"
    if [[ -n "${value}" ]]; then
        printf "%s" "${value}"
        return 0
    fi
    repo_state_value "${key}"
}

extract_ollama_host_dir() {
    local match
    match="$(awk '/\/root\/\.ollama/ && $1 == "-" { print $2; exit }' "${ROOT_DIR}/docker-compose.yml" 2>/dev/null || true)"
    match="${match%%:/root/.ollama*}"
    printf "%s" "${match}"
}

resolve_project_path() {
    local path="$1"

    [[ -n "${path}" ]] || return 1
    if [[ "${path}" == /* ]]; then
        case "${path}" in
            "${ROOT_DIR}"/*)
                printf "%s" "${path}"
                return
                ;;
            *)
                return 1
                ;;
        esac
    fi

    path="${path#./}"
    path="${path#/}"
    printf "%s/%s" "${ROOT_DIR}" "${path}"
}

run_cmd() {
    local description="$1"
    shift

    if [[ "${DRY_RUN}" -eq 1 ]]; then
        print_info "[dry-run] $*"
        return
    fi

    "$@"
    print_success "${description}"
}

run_root_cmd() {
    local description="$1"
    shift

    if [[ "${DRY_RUN}" -eq 1 ]]; then
        print_info "[dry-run] sudo $*"
        return
    fi

    as_root "$@"
    print_success "${description}"
}

remove_path() {
    local label="$1"
    local path="$2"

    if [[ ! -e "${path}" && ! -L "${path}" ]]; then
        print_info "${label} not present: ${path}"
        return
    fi

    if [[ "${DRY_RUN}" -eq 1 ]]; then
        print_info "[dry-run] rm -rf -- ${path}"
        return
    fi

    rm -rf -- "${path}"
    print_success "Removed ${label}: ${path}"
}

remove_root_path() {
    local label="$1"
    local path="$2"

    if [[ ! -e "${path}" && ! -L "${path}" ]]; then
        print_info "${label} not present: ${path}"
        return
    fi

    if [[ "${DRY_RUN}" -eq 1 ]]; then
        print_info "[dry-run] sudo rm -rf -- ${path}"
        return
    fi

    as_root rm -rf -- "${path}"
    print_success "Removed ${label}: ${path}"
}

run_compose_down() {
    if ! command_exists docker; then
        print_warning "Docker is not installed on this host. Skipping Docker Compose teardown."
        return
    fi

    if ! docker compose version >/dev/null 2>&1; then
        print_warning "Docker Compose plugin is not available. Skipping Docker Compose teardown."
        return
    fi

    if [[ "${DRY_RUN}" -eq 1 ]]; then
        print_info "[dry-run] (cd ${ROOT_DIR} && docker compose down --volumes --remove-orphans)"
        return
    fi

    (
        cd "${ROOT_DIR}"
        docker compose down --volumes --remove-orphans
    )
    print_success "Docker Compose stack removed for this repository"
}

remove_managed_override() {
    local override_file="${ROOT_DIR}/docker-compose.override.yml"

    if [[ ! -f "${override_file}" ]]; then
        print_info "docker-compose.override.yml not present"
        return
    fi

    if grep -qF "${MANAGED_OVERRIDE_MARKER}" "${override_file}"; then
        remove_path "installer-managed docker-compose.override.yml" "${override_file}"
        return
    fi

    print_warning "Preserving docker-compose.override.yml because it is not marked as installer-managed"
}

remove_tls_certs_if_manifest_allows() {
    local generated_tls
    local cert_dir="${ROOT_DIR}/deploy/certs"

    generated_tls="$(repo_state_value "CERTS_GENERATED_BY_INSTALLER" || repo_state_value "GENERATED_TLS_CERTS" || true)"
    if bool_is_true "${generated_tls}"; then
        remove_path "installer-generated TLS certificate directory" "${cert_dir}"
        return
    fi

    if [[ -d "${cert_dir}" ]]; then
        print_warning "Preserving deploy/certs because installer ownership is not proven"
    else
        print_info "deploy/certs not present"
    fi
}

remove_ollama_state() {
    local ollama_dir
    local resolved_dir

    ollama_dir="$(repo_state_value "OLLAMA_HOST_DIR" || true)"
    if [[ -z "${ollama_dir}" ]]; then
        ollama_dir="$(extract_ollama_host_dir)"
    fi

    if [[ -z "${ollama_dir}" ]]; then
        print_info "No Ollama host directory was detected from manifest or docker-compose.yml"
        return
    fi

    if ! resolved_dir="$(resolve_project_path "${ollama_dir}")"; then
        print_warning "Preserving Ollama host directory because it resolves outside the repository scope: ${ollama_dir}"
        return
    fi

    remove_path "Ollama host directory" "${resolved_dir}"
}

restore_service_state() {
    local unit="$1"
    local enabled="$2"
    local active="$3"

    if ! systemd_unit_exists "${unit}"; then
        print_info "Systemd unit not present, skipping restore: ${unit}"
        return
    fi

    if bool_is_true "${enabled}" && bool_is_true "${active}"; then
        run_root_cmd "Restored ${unit} to enabled+active" systemctl enable --now "${unit}"
        return
    fi

    if bool_is_true "${enabled}" && ! bool_is_true "${active}"; then
        run_root_cmd "Restored ${unit} enablement" systemctl enable "${unit}"
        if [[ "${DRY_RUN}" -eq 1 ]]; then
            print_info "[dry-run] sudo systemctl stop ${unit}"
        else
            as_root systemctl stop "${unit}" >/dev/null 2>&1 || true
            print_success "Restored ${unit} to enabled+stopped"
        fi
        return
    fi

    if ! bool_is_true "${enabled}" && bool_is_true "${active}"; then
        run_root_cmd "Restored ${unit} active state" systemctl start "${unit}"
        if [[ "${DRY_RUN}" -eq 1 ]]; then
            print_info "[dry-run] sudo systemctl disable ${unit}"
        else
            as_root systemctl disable "${unit}" >/dev/null 2>&1 || true
            print_success "Restored ${unit} to disabled+active"
        fi
        return
    fi

    if [[ "${DRY_RUN}" -eq 1 ]]; then
        print_info "[dry-run] sudo systemctl disable --now ${unit}"
    else
        as_root systemctl disable --now "${unit}" >/dev/null 2>&1 || true
        print_success "Restored ${unit} to disabled+stopped"
    fi
}

remove_manifest_owned_packages() {
    local package_line
    local -a requested_packages=()
    local -a installed_packages=()
    local pkg

    package_line="$(host_state_value "OWNED_APT_PACKAGES" || true)"
    if [[ -z "${package_line}" ]]; then
        package_line="$(repo_state_value "APT_PACKAGES_INSTALLED_BY_INSTALLER" || true)"
    fi
    if [[ -z "${package_line}" ]]; then
        print_warning "Manifest does not contain installer-owned apt package data; host package rollback is skipped"
        return
    fi

    read -r -a requested_packages <<<"${package_line}"
    for pkg in "${requested_packages[@]}"; do
        dpkg -s "${pkg}" >/dev/null 2>&1 && installed_packages+=("${pkg}")
    done

    if [[ "${#installed_packages[@]}" -eq 0 ]]; then
        print_info "No manifest-owned apt packages are currently installed"
        return
    fi

    run_root_cmd "Purged manifest-owned apt packages" env DEBIAN_FRONTEND=noninteractive apt-get purge -y "${installed_packages[@]}"
}

rollback_docker_repo_and_keyring() {
    local managed_repo backup_file added_keyring
    local repo_file="/etc/apt/sources.list.d/docker.list"
    local keyring_file="/etc/apt/keyrings/docker.asc"

    managed_repo="$(host_state_value "OWNED_DOCKER_REPO_FILE" || repo_state_value "INSTALLER_MANAGED_DOCKER_REPO_FILE" || true)"
    backup_file="$(host_state_value "OWNED_DOCKER_REPO_BACKUP" || repo_state_value "DOCKER_REPO_FILE_BACKUP" || true)"
    added_keyring="$(host_state_value "OWNED_DOCKER_KEYRING" || repo_state_value "INSTALLER_ADDED_DOCKER_KEYRING" || true)"

    if bool_is_true "${managed_repo}"; then
        if [[ -n "${backup_file}" && -f "${backup_file}" ]]; then
            run_root_cmd "Restored pre-install Docker repo file" cp "${backup_file}" "${repo_file}"
        else
            remove_root_path "installer-managed Docker repo file" "${repo_file}"
        fi
    else
        print_info "Docker repo file is preserved because installer ownership is not proven"
    fi

    if bool_is_true "${added_keyring}"; then
        remove_root_path "installer-added Docker keyring" "${keyring_file}"
    else
        print_info "Docker keyring is preserved because installer ownership is not proven"
    fi
}

rollback_docker_group_membership() {
    local added_membership install_user

    added_membership="$(host_state_value "OWNED_DOCKER_GROUP_MEMBERSHIP" || repo_state_value "INSTALLER_ADDED_USER_TO_DOCKER_GROUP" || true)"
    install_user="$(host_state_value "OWNED_DOCKER_GROUP_USER" || repo_state_value "INSTALL_USER" || true)"

    if ! bool_is_true "${added_membership}"; then
        print_info "docker group membership is preserved because installer ownership is not proven"
        return
    fi

    [[ -n "${install_user}" ]] || {
        print_warning "INSTALL_USER is missing from manifest; cannot roll back docker group membership"
        return
    }

    if ! getent group docker >/dev/null 2>&1; then
        print_info "docker group not present"
        return
    fi

    if ! id "${install_user}" >/dev/null 2>&1; then
        print_warning "Install user '${install_user}' is not present on this host; skipping docker group rollback"
        return
    fi

    if ! id -nG "${install_user}" | grep -qw docker; then
        print_info "User '${install_user}' is not currently in the docker group"
        return
    fi

    if [[ "${DRY_RUN}" -eq 1 ]]; then
        print_info "[dry-run] sudo gpasswd -d ${install_user} docker"
        return
    fi

    as_root gpasswd -d "${install_user}" docker >/dev/null 2>&1 || true
    print_success "Removed '${install_user}' from the docker group"
}

rollback_ollama_host_install() {
    local preexisting_ollama install_owned_ollama service_present service_enabled service_active
    local bin_path service_fragment

    preexisting_ollama="$(preferred_state_value "PREINSTALL_OLLAMA_CLI" || true)"
    install_owned_ollama="$(host_state_value "OWNED_OLLAMA_CLI" || repo_state_value "INSTALLER_INSTALLED_OLLAMA_CLI" || true)"
    service_present="$(preferred_state_value "PREINSTALL_OLLAMA_SERVICE_PRESENT" || true)"
    service_enabled="$(preferred_state_value "PREINSTALL_OLLAMA_SERVICE_ENABLED" || true)"
    service_active="$(preferred_state_value "PREINSTALL_OLLAMA_SERVICE_ACTIVE" || true)"
    bin_path="$(host_state_value "OWNED_OLLAMA_BIN_PATH" || preferred_state_value "POSTINSTALL_OLLAMA_BIN_PATH" || true)"
    service_fragment="$(host_state_value "OWNED_OLLAMA_SERVICE_FRAGMENT" || preferred_state_value "POSTINSTALL_OLLAMA_SERVICE_FRAGMENT" || true)"

    if bool_is_true "${install_owned_ollama}" && ! bool_is_true "${preexisting_ollama}"; then
        if systemd_unit_exists ollama.service; then
            if [[ "${DRY_RUN}" -eq 1 ]]; then
                print_info "[dry-run] sudo systemctl disable --now ollama.service"
            else
                as_root systemctl disable --now ollama.service >/dev/null 2>&1 || true
                print_success "Stopped and disabled installer-owned ollama.service"
            fi
        fi

        if [[ -n "${service_fragment}" ]]; then
            case "${service_fragment}" in
                /etc/systemd/system/*|/usr/lib/systemd/system/*|/lib/systemd/system/*)
                    remove_root_path "installer-owned Ollama service unit" "${service_fragment}"
                    if [[ "${DRY_RUN}" -eq 1 ]]; then
                        print_info "[dry-run] sudo systemctl daemon-reload"
                    else
                        as_root systemctl daemon-reload >/dev/null 2>&1 || true
                        print_success "Reloaded systemd after Ollama unit removal"
                    fi
                    ;;
                "")
                    print_info "No Ollama service fragment path was recorded"
                    ;;
                *)
                    print_warning "Preserving Ollama service fragment because the path is outside expected systemd locations: ${service_fragment}"
                    ;;
            esac
        fi

        if [[ -n "${bin_path}" ]]; then
            case "${bin_path}" in
                /usr/local/bin/ollama|/usr/bin/ollama)
                    remove_root_path "installer-owned Ollama binary" "${bin_path}"
                    ;;
                *)
                    print_warning "Preserving Ollama binary because the path is outside expected locations: ${bin_path}"
                    ;;
            esac
        fi

        return
    fi

    if bool_is_true "${service_present}"; then
        restore_service_state "ollama.service" "${service_enabled}" "${service_active}"
    else
        print_info "Ollama service state is preserved because no pre-install service was recorded"
    fi
}

rollback_docker_service_state_if_needed() {
    local owned_docker_engine pre_docker_cli pre_enabled pre_active

    owned_docker_engine="$(host_state_value "OWNED_DOCKER_ENGINE" || true)"
    if bool_is_true "${owned_docker_engine}"; then
        print_info "Docker service rollback is covered by removing installer-owned Docker packages"
        return
    fi

    pre_docker_cli="$(preferred_state_value "PREINSTALL_DOCKER_CLI" || true)"
    pre_enabled="$(preferred_state_value "PREINSTALL_DOCKER_SERVICE_ENABLED" || true)"
    pre_active="$(preferred_state_value "PREINSTALL_DOCKER_SERVICE_ACTIVE" || true)"

    if ! bool_is_true "${pre_docker_cli}"; then
        print_info "Docker service state is not restored because Docker did not pre-exist install according to the manifest"
        return
    fi

    if ! command_exists docker; then
        print_info "Docker command is no longer present; skipping Docker service-state restore"
        return
    fi

    restore_service_state "docker.service" "${pre_enabled}" "${pre_active}"
}

remove_project_state() {
    run_compose_down
    remove_path ".env" "${ROOT_DIR}/.env"
    remove_path "deploy/krb5.conf" "${ROOT_DIR}/deploy/krb5.conf"
    remove_managed_override
    remove_ollama_state
    remove_tls_certs_if_manifest_allows
}

cleanup_host_state() {
    local backup_file

    backup_file="$(host_state_value "OWNED_DOCKER_REPO_BACKUP" || true)"
    if [[ -n "${backup_file}" ]]; then
        remove_root_path "durable Docker repo backup" "${backup_file}"
    fi
    remove_root_path "durable host manifest" "${HOST_STATE_FILE}"

    if [[ "${DRY_RUN}" -eq 1 ]]; then
        print_info "[dry-run] sudo rmdir --ignore-fail-on-non-empty ${HOST_STATE_DIR}/backups"
        print_info "[dry-run] sudo rmdir --ignore-fail-on-non-empty ${HOST_STATE_DIR}"
        return
    fi

    as_root rmdir --ignore-fail-on-non-empty "${HOST_STATE_DIR}/backups" >/dev/null 2>&1 || true
    as_root rmdir --ignore-fail-on-non-empty "${HOST_STATE_DIR}" >/dev/null 2>&1 || true
    print_success "Durable host manifest state cleaned up"
}

run_factory_reset() {
    if [[ ! -f "${STATE_FILE}" && ! -f "${HOST_STATE_FILE}" ]]; then
        print_warning "Install manifest is missing. Factory-reset will be partial and limited to provable project-local cleanup."
        return
    fi

    if [[ ! -f "${STATE_FILE}" && -f "${HOST_STATE_FILE}" ]]; then
        print_warning "Repo-local manifest is missing; continuing with durable host manifest for installer-owned host rollback"
    fi

    rollback_ollama_host_install
    remove_manifest_owned_packages
    rollback_docker_repo_and_keyring
    rollback_docker_group_membership
    rollback_docker_service_state_if_needed
    cleanup_host_state
}

schedule_repo_removal() {
    if [[ "${DRY_RUN}" -eq 1 ]]; then
        print_info "[dry-run] write deferred self-delete helper ${HELPER_FILE}"
        print_info "[dry-run] deferred background removal of ${ROOT_DIR}, ${LOG_FILE}, and ${HELPER_FILE}"
        return
    fi

    cat >"${HELPER_FILE}" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
target_dir="$1"
log_file="$2"
helper_file="$3"

sleep 1
rm -rf -- "${target_dir}"
rm -f -- "${log_file}"
rm -f -- "${helper_file}"
EOF
    chmod 700 "${HELPER_FILE}"
    nohup bash "${HELPER_FILE}" "${ROOT_DIR}" "${LOG_FILE}" "${HELPER_FILE}" >/dev/null 2>&1 </dev/null &

    print_success "Deferred repository self-delete has been scheduled"
}

confirm_uninstall() {
    local answer

    if [[ "${DRY_RUN}" -eq 1 || "${ASSUME_YES}" -eq 1 ]]; then
        return
    fi

    if [[ ! -t 0 ]]; then
        die "Non-interactive uninstall requires --yes"
    fi

    printf "Proceed with %s uninstall for %s? [y/N]: " "$(mode_label)" "${ROOT_DIR}"
    read -r answer
    case "${answer,,}" in
        y|yes)
            ;;
        *)
            die "Uninstall cancelled by user"
            ;;
    esac
}

parse_args() {
    while [[ "$#" -gt 0 ]]; do
        case "$1" in
            --dry-run)
                DRY_RUN=1
                ;;
            --yes)
                ASSUME_YES=1
                ;;
            --factory-reset)
                FACTORY_RESET=1
                ;;
            --remove-repo)
                REMOVE_REPO=1
                ;;
            --help|-h)
                usage
                exit 0
                ;;
            *)
                die "Unknown argument: $1"
                ;;
        esac
        shift
    done
}

validate_args() {
    if [[ "${REMOVE_REPO}" -eq 1 && "${FACTORY_RESET}" -ne 1 ]]; then
        die "--remove-repo requires --factory-reset"
    fi

    if [[ "${REMOVE_REPO}" -eq 1 && "${ASSUME_YES}" -ne 1 && "${DRY_RUN}" -ne 1 ]]; then
        die "--remove-repo requires --yes unless --dry-run is used"
    fi
}

mode_label() {
    if [[ "${REMOVE_REPO}" -eq 1 ]]; then
        printf "factory-reset + remove-repo"
        return
    fi
    if [[ "${FACTORY_RESET}" -eq 1 ]]; then
        printf "factory-reset"
        return
    fi
    printf "safe"
}

print_plan() {
    print_info "Selected uninstall mode: $(mode_label)"
    print_info "Project cleanup:"
    print_info "- remove Docker Compose stack, network, and named volumes for this repository"
    print_info "- remove project-local .env, deploy/krb5.conf, installer-managed docker-compose.override.yml, .ollama, and .install"
    print_info "- remove deploy/certs only when the install manifest proves install.sh generated them"
    if [[ "${FACTORY_RESET}" -eq 1 ]]; then
        print_info "Factory-reset additions:"
        print_info "- remove exact apt packages recorded as installer-owned in the durable host manifest"
        print_info "- restore or remove Docker repo/keyring only when manifest ownership exists"
        print_info "- restore or remove Docker/Ollama host service state only when manifest proves installer changed it"
        print_info "- remove docker group membership only when manifest proves installer added it"
        print_info "- remove durable host ownership state after successful rollback"
    fi
    if [[ "${REMOVE_REPO}" -eq 1 ]]; then
        print_info "Repo removal:"
        print_info "- schedule deferred background deletion of the repository directory, this uninstall log, and the helper itself"
    fi
    print_info "Preserved on purpose:"
    print_info "- unrelated Docker assets"
    print_info "- deploy/sso keytab material"
    print_info "- host dependencies without manifest ownership proof"
    print_info "Uninstall log: ${LOG_FILE}"
    if [[ "${REMOVE_REPO}" -eq 1 ]]; then
        print_info "Self-delete helper: ${HELPER_FILE}"
    fi
}

main() {
    parse_args "$@"
    validate_args
    exec > >(tee -a "${LOG_FILE}") 2>&1

    print_plan
    confirm_uninstall

    remove_project_state
    if [[ "${FACTORY_RESET}" -eq 1 ]]; then
        run_factory_reset
    fi
    remove_path ".install" "${ROOT_DIR}/.install"
    if [[ "${REMOVE_REPO}" -eq 1 ]]; then
        schedule_repo_removal
    fi

    print_success "Uninstall flow completed"
}

main "$@"
